### PR TITLE
Feature/vice snapshot monitor

### PR DESCRIPTION
**Pull request by elliot2**
**VICE Snapshot Monitor and Sprite Grabber**

 Provides a retro-style monitor interface where users can issue commands to monitor and modify
 graphical and memory data, essentially helping developers or enthusiasts dive deeper
 into the inner workings of the Commodore 64's VIC-II graphics chip.

 This tool allows users to interact with the emulator's snapshot memory. 
 Users can type commands to explore memory areas (e.g., "mem" for memory inspection), 
 edit specific memory values, manage color settings, and even "grab" sprite data from specific 
 memory locations.
  
 For example, with commands like "grab n" or "grabcols," users can capture and 
 load sprite data and colors into the editor, making it easy to replicate and edit sprites.

snapshots

### CODE REVIEW

**Comment by elliot2** [comment]
There were some addressing errors, but should now work ok.  Let me know if you can test it out?

**Comment by elliot2** [comment]
Added a repeatable grabmem function, ie. if you open a snapshot you can do :

```
grabcols
grab
grabmem
```
This command can repeat, ie. push [enter] again to grab next 64 bytes, and so on.


You can also use the follow to return to use another address  :
```
grabmem 0x400
```

image

**Comment by elliot2** [comment]
Added an icon to toggle the monitor window.
image

**Comment by Esshahn** [comment]
Wow, that looks incredible! I will give it a test tomorrow, will also try to push the recent PRs asap. Can you provide a quick tutorial or link on how to setup vice to use the monitor? When we introduce this amazing feature, we should also explain clearly how it works. 

I'm unsure about putting the monitor in the tools palette though. I always felt this should be restricted to editing the sprites. We could easily move the monitor in the menu, how about giving it a separate section in the "edit" menu

New file
Load file...
Save file...
----------
VICE Snapshot Monitor

**Comment by elliot2** [comment]
Sounds good, updated.

image

**Comment by elliot2** [comment]
Video tutorial :
https://www.youtube.com/watch?v=UdFc7yFCZGw

**Comment by Esshahn** [comment]
I've tested the feature and think it's utterly brilliant. Let me know if you're fine with merging this into staging now.

**Comment by elliot2** [comment]
Yes,  that sounds great.  Go ahead. 🙂

**Pull request merged**
