### PR TITLE
Add four up, 2up v, 2up h multi sprite mode

### PR DESCRIPTION
**Pull request by elliot2**
I have rebuilt it against staging.

When the first of any 4 sprites is selected, an option will appear to display in four up mode.
The editor resolution for specifically drawing and erasing will spread over multiple sprites.
This enables you to create a larger sprite composition.  If there are not enough sprites to spread the indexing,
the toggle option will not appear.

Thanks

description

### CODE REVIEW

**Comment by elliot2** [comment]
Added additional single, two up horizontal, and vertical, along with 4 up mode.

description2

**Comment by Esshahn** [comment]
That is absolutely amazing work, I love it! I was wondering if you could give this idea a thought: what about making the feature more versatile and letting the user decide on the grid size? I imagine it could work like this:
Instead of predefined buttons for each grid layout, we could introduce this UI change in the editor window:

Multisprite layout: [ NUMBER ] x [ NUMBER ]

A 4up layout would be achievable by setting the input fields to [ 2 ] x [ 2 ] and the Antiriad sprite would be [ 1 ] x [ 2 ] for example.

I think, this is a highly desirable feature for many users. It's already, so thank you so much. I will try to get everything pushed to main this week (busy week).

**Comment by Esshahn** [comment]
Also, on a random note, let me say that I've tried to implement this idea several times and failed. Looking at your code makes it seem almost trivial. Congrats, great work.

**Comment by elliot2** [comment]
No worries, and thanks a lot for making this project available as open source.
Currently the fill, and move do not work over multi sprite,  I want to contribute more to it, at least for beta testing.

What do you think about a batch rotation function?

**Comment by Esshahn** [comment]
I would love to have you onboard, Spritemate is used quite regularly and I haven't been able to support the project in the way it could. As for features: yeah, rotation would be cool, not only as batch but for each sprite. It's a bit tricky because or the 24x21 format.

I've collected some feature requests in the past: https://github.com/Esshahn/spritemate/milestone/3
In my view 3 of them are highly desirable:

1. A selection tool: https://github.com/Esshahn/spritemate/issues/44
This would let you draw a rectangle around an area and then do isolated operations on the pixels inside, just like in any other paint tool (e.g. move the area around)

2. Basic animation functionality: https://github.com/Esshahn/spritemate/issues/125 (sorry, had to chuckle about the horrible scribble)
It would be great to see animations. It could be similar to other animation tools, maybe a separate window where one could drag'n'drop the sprites into and define an animation speed.

3. Overlay & Canvas: https://github.com/Esshahn/spritemate/issues/127 (german feature request)
Basic idea is to have an extra canvas where one could arrange sprites onto, e.g. to arrange bigger multisprite objects. It would be a bit similar to the new Xup feature, but with more freedom to arrange sprites, e.g. overlay them.
I've started working on this and failed, but I like the concept.

**Comment by elliot2** [comment]
That would be great, sounds like some good features there!  
I have opened a new PR with the user config layout if you want to check that.
https://github.com/Esshahn/spritemate/pull/214

**Pull request closed without merging**
