### PR TITLE
Webpackify the spritemate build

### PR DESCRIPTION
**Pull request by nurpax**
How about something like this to clean up the build?  Below is the main commit, but I had to move some files around to basically get rid of the 'dist/' directory (as that's usually a dir with only build outputs).

I know this doesn't merge directly as some changes had gone in that conflict.  But if you're interested, I can rebase this.

IMO it's quite a bit nicer that this doesn't mix "source files" with "build outputs" in 'dist/' directory anymore.  And "yarn start" runs webpack-dev-server which gives you super fast edit-save-debug cycle.

Also wanted to do a bit of clean up to get my feet wet with this code.  If I do anything about that Electron patch, I'd probably need this type of clean up anyway.

---
Add webpack.config.js and make all the JS files build with
webpack/babel.

This adds webpack-dev-server support in the package.json so that the
app can be started in development mode with:

yarn start

Webpack dev server will automatically watch any files under 'src/' (or
any deps) and recompile as necessary and reloads the page in the
browser automatically.

To build the site, run:

yarn build

This will output the required js/css/html files needed under 'dist/'.
The 'dist/' directory has been completely removed from Git and is
treated as temporary files only.  The files previously under 'dist/'
have been mostly moved to 'src/'.

The jquery-ui theme was not using default colors, so I had to import
the .css file under src/ instead of using import
'webpack-jquery-ui/css' or similar (this would allow importing CSS
directly from npm package instead of having a separate copy of the CSS
file under 'src/'.

Jquery and jquery-ui JS bits are now pulled directly from a package
and baked into the JS bundle.

### CODE REVIEW

**Comment by nurpax** [comment]
Rebased to latest upstream master.

**Comment by Esshahn** [comment]
I will take some time over the weekend to give this more thought. Thank you for sharing your experience with me, I greatly appreciate this. On my feature branch, I already renamed the babel folder and I've installed webpack (which gave me a hard time as everything broke and I needed to manually update node to get it going again). 

I know webpack is the way to go, but I'm not 100% sold yet in regards to Spritemate. Yes, I can reduce the footprint of my index.html by not including all the scripts, but then again I have to import them at other places in the code. To me it feels a bit like optimizing something that is currently pretty simple and understandable for newbies as well. The more stuff I add, the more complicated it gets for hobby devs like me. Babel transpiles my code into the dist folder and that's it. I like the simplicity of this setup and I could even stop using babel and code plain vanilla JS and nothing would break.

Having said that, I'm missing out on a lot of benefits when not using webpack and I will look into it for sure just to improve and learn. Your suggestions help me in achieving that. Thank you!

**Comment by nurpax** [comment]
I didn't think of footprint reduction as a benefit (although it probably will be reduced with this).  Webpack would be more about

* switching the proper ES6 imports everywhere (granted this adds a few lines of more code, but it also clearly defines module boundaries).
* an excellent dev environment (webpack-dev-server is really fast at recompiles and automatically refreshes your browser window when you save a source file, be it JS, CSS or HTML)
* enables some other build changes (like say generating a different index.html for Electron app if needed, as index.html is now run through a templating engine).
* it also can be configured to produce hashed file names of all your assets (css, js) so that when you update a CSS or a JS file, browsers will correctly invalidate the browser cache.  So no stale browser cache, no forced reloads, ever.
* separate build outputs from source code (everything under 'dist/' is now a result of a webpack build, so you can just nuke it and rebuild, and everything needed for deployment will be there)

My web experience is very much tainted by working on React apps though where webpack is the standard.  Working with a codebase not using webpack but direct <script> includes is more daunting to me than using webpack.

But I totally get this:

> I like the simplicity of this setup and I could even stop using babel and code plain vanilla JS and nothing would break.

Webpack does bring certainly bring a certain amount of complexity.. especially if you're not familiar with it.  It does have a bit of a learning curve.  Fortunately webpack 4.0 (which I used here) is quite a bit nicer than what webpack used to be in terms of configuration.  The config I wrote in this PR is also pretty simple, and I was able to pretty much write it from scratch without copy&pasting, which I guess speaks to its simplicity (in the React world, webpack configs are usually pretty advanced/complicated.)

Anyway.. You should definitely choose what you feel like works best for you.  I provided this as a working example of using webpack (although AFAIAC it's good enough to be merged).  My main motivation was that this should make it somewhat easier to add a cleaner Electron version of Spritemate.

**Comment by Esshahn** [comment]
Is .eslintrc.js essential for the setup?

**Comment by nurpax** [comment]
.eslintrc.js is optional.  It's the config file used for "npm lint" target.  So if you want to use eslint, then you need the config file (and using eslint is of course optional too, but I find it really helpful to use it).  

It's not super well configured though, there's a lot of warnings with the current settings (you'd want to start with rules that produce mostly a clean output, then add rules one by one).

**Comment by Esshahn** [comment]
cheers! I followed your recommendation and moved some files around, also not committing the dist/js anymore. The next big step would be to use webpack and touch all files and configs. I'm not ready to do that, yet, but your comments helped me a lot understanding how it would and should work.

**Comment by nurpax** [comment]
Sounds good!  Makes sense to bring on more complexity when you really need it and understand the details.  This PR might be a handy reference should you later decide to switch to webpack.

**Pull request closed without merging**
